### ISSUE TITLE
Integrating with Nerf Studio

### ISSUE THREAD

**Issue by dlazares** [dengnianchen/fovnerf#1]
Hi Nianchen Deng,

Thanks for writing such an interesting paper.
I'm interested in integrating this into the [nerf studio](https://github.com/nerfstudio-project/nerfstudio) repo so more people have access to your amazing work and can build off it!

If that seems good with you, we can use this issue to track and discuss the progress of this work.
Looking forward to your code release!

**Comment by dengnianchen** [comment]
Hi, thanks for your interest in our work. Our source code is now released with documentation. Feel free to integrate it into your project with reference. If you have any questions, please feel free to ask.

**Comment by dengnianchen** [comment]
> Hi Nianchen Deng,
> 
> Thanks for writing such an interesting paper. I'm interested in integrating this into the [nerf studio](https://github.com/nerfstudio-project/nerfstudio) repo so more people have access to your amazing work and can build off it!
> 
> If that seems good with you, we can use this issue to track and discuss the progress of this work. Looking forward to your code release!

Hi, thanks for your interest in our work. Our source code is now released with documentation. Feel free to integrate it into your project with reference. If you have any questions, please feel free to ask.
