### ISSUE TITLE
Loading real-world scenes from Colmap

### ISSUE THREAD

**Issue by dlazares** [dengnianchen/fovnerf#3]
Hi, I'm trying to test on my own dataset processed using Colmap. I have successfully tested this dataset in instant-ngp, so I know it works decently well. I've also run fovnerf successfully on pre-trained classroom, pre-trained sittingroom, and locally trained classroom.

I've tried my best to figure out the dataset format from the code and made this [script](https://gist.github.com/dlazares/85fa7de8eabe257408d1c237b0977900) to try and process the colmap dataset into your json data file format.
However, when I run my dataset on it I get output with nan. My theory is something to do with the rotation matrices but I'm not sure.
Additionally, the Google Drive dataset only has the synthetic scenes. It would be helpful if you could also attach the real-world scene data and files you used to train the network.

Could you help me out?
I've also attached my dataset here. [Drive link](https://drive.google.com/drive/folders/1xReL0SRcU0LZCq948LehM8m8IvQZZhrg?usp=sharing)

**Comment by dengnianchen** [comment]
An constraint of fovnerf is that all viewpoints must be in the inner sphere, i.e. the norm of every position in dataset must be less than the near depth specified in the dataset.
