### ISSUE TITLE
 used for virtual reality scenes created using the Unity engine

### ISSUE THREAD

**Issue by shayebuhuidewo** [dengnianchen/fovnerf#4]
Hello, I have carefully read your paper and I find it very attractive. However, I have a question that I would like to consult with you. I would like to know if your method can be effectively used for real-time rendering of virtual reality scenes created using the Unity engine. If it is indeed possible, could you provide some effective implementation guidance? Sincerely thank you for your time and professional knowledge

**Comment by dengnianchen** [comment]
Hello, I have tried to integrate fovnerf in Unity, and the solution is to call tensorRT through the C++ plug-in for inference. But it encounters a program crash of unknown reason when it runs, and I haven't been able to solve it. So then I adopted a pure C++ implementation based on opengl+tensorRT.

**Comment by shayebuhuidewo** [comment]
Hello, can you provide me with the dome or code to integrate your functions into Unity? I am very interested in this, but I am a beginner. Thank you very much for your help.

**Comment by dengnianchen** [comment]
Here is a scratch code, including dll plugin written in cpp and the C# code which invokes dll plugin. This is not a complete project and cannot run directly. Also note that the code structure in the dll plugin is out of update so it is different from the code in cpp/fnr_core of this repo. I'm sorry for not having enough time to make it runnable. So I just attach this scratch as an example, to show how the network inference can be done using tensorRT in Unity.

You can also google using keywords "Unity TensorRT" to search for some useful guides proposed by other guys.

Thanks.

[unity_trt.zip](https://github.com/dengnianchen/fovnerf/files/11665533/unity_trt.zip)

**Comment by shayebuhuidewo** [comment]
Thank you very much for sharing your knowledge. I appreciate your help.
