### ISSUE TITLE
VR integration

### ISSUE THREAD

**Issue by CarettaCaretta11** [dengnianchen/fovnerf#5]
How did you get the `trt` inference engine (e.g. from `./view_gl ../nets/barbershop`) integrated in a VR headset during your research? What are some ways of doing it that you are aware of?

**Comment by dengnianchen** [comment]
HTC Vive provides a C++ SDK that supports integration with opengl.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Kamran ***@***.***>
Sent: Monday, August 14, 2023 3:21:49 PM
To: dengnianchen/fovnerf ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dengnianchen/fovnerf] VR integration (Issue #5)


How did you get the trt inference engine (e.g. from ./view_gl ../nets/barbershop) integrated in a VR headset during your research? What are some ways of doing it that you are aware of?

―
